FROM node:16
RUN mkdir /Chatapp
WORKDIR /Chatapp
RUN useradd -d /Chatapp -M -g 1000 ChatAppDockerUser
RUN chown :1000 /Chatapp
COPY package*.json ./
COPY server/ ./server
#CHATAPP PORT
EXPOSE 8000
RUN npm install
CMD [ "node", "server/index.js" ]
