FROM node:16
RUN mkdir /Chatapp
WORKDIR /Chatapp
RUN useradd -d /Chatapp -M -g 1000 ChatAppDockerUser
RUN chown :1000 /Chatapp
COPY ../ChatApp-Client/html server/Client/
COPY ../ChatApp-Client/JS server/Client/JS/
COPY package.json ./
COPY yarn.lock ./
COPY server/ ./server
#CHATAPP PORT
EXPOSE 8000
RUN yarn
CMD [ "yarn", "run", "start" ]