version: '3'
services:
  chatapp:
    build: .
    container_name: ChatApp
    # environment:
    #   - SAVE_FILE=/config/SaveChat.json
    #   - CERT=/config/ssl/wss.crt
    #   - KEY=/config/ssl/wss.key
    volumes:
      - ./config:/config
    ports:
      - 8999:8999
    restart: unless-stopped